name: CICD

on:
  push:
    branches: [deploy-to-ec2]

jobs:
  build:
    runs-on: [ubuntu-latest]
    steps:
      - name: Checkout source
        uses: actions/checkout@v3
      - name: Setup java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Build Project
        run: mvn clean install -DskipTests
      - name: login to docker hub
        run: docker login -u ${{secrets.DOCKER_USERNAME}} -p ${{secrets.DOCKER_PASSWORD}}
      - name: Build docker image
        run: docker build -t ike20743/springboot-image .
      - name: Publish image to docker hub
        run: docker push ike20743/springboot-image:latest

  deploy:
    needs: build
    runs-on: [ip-172-31-18-231]
    steps:
      - name: Pull Image free docker hub
        run: docker pull ike20743/springboot-image:latest
      - name: Delete old container
        run: docker rm -f springboot-image:latest
      - name: Run docker container
        run: docker run -d -p 8080:8080 --name springboot-image-container ike20743/springboot-image:latest




